apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-middleware
  labels:
    user: davyj0nes
    function: poc
spec:
  selector:
    matchLabels:
      app: prometheus-middleware
  endpoints:
  - port: "web"