apiVersion: v1
kind: Service
metadata:
  name:  prometheus-middleware
spec:
  selector:
    app:  prometheus-middleware
  type:  NodePort
  ports:
  - name:  main-port
    port:  8080
    targetPort:  8080
